CREATE VIEW DB_Foreign_Keys
AS

SELECT	T1.CONSTRAINT_NAME,
		T3.CONSTRAINT_TYPE,
		T1.TABLE_NAME,
		T1.COLUMN_NAME,
		T2.UPDATE_RULE,
		T2.DELETE_RULE,
		T2.UNIQUE_CONSTRAINT_NAME,
		T5.CONSTRAINT_TYPE AS CONSTRAINT_TYPE_2 ,
		T4.TABLE_NAME AS TABLE_NAME_2,
		T4.COLUMN_NAME AS COLUMN_NAME_2
FROM 
		(SELECT CONSTRAINT_NAME,TABLE_NAME,COLUMN_NAME
		FROM INFORMATION_SCHEMA.KEY_COLUMN_USAGE ) T1
LEFT JOIN 
		(SELECT CONSTRAINT_NAME,UNIQUE_CONSTRAINT_NAME,UPDATE_RULE,DELETE_RULE 
		FROM INFORMATION_SCHEMA.REFERENTIAL_CONSTRAINTS) T2
ON T1.CONSTRAINT_NAME = T2.CONSTRAINT_NAME 

LEFT JOIN 
		(SELECT CONSTRAINT_NAME,CONSTRAINT_TYPE FROM INFORMATION_SCHEMA.TABLE_CONSTRAINTS) T3
ON T1.CONSTRAINT_NAME = T3.CONSTRAINT_NAME

LEFT JOIN
		(
		SELECT DISTINCT T4_1.*
		FROM 
				(SELECT CONSTRAINT_NAME,TABLE_NAME,COLUMN_NAME
				FROM INFORMATION_SCHEMA.KEY_COLUMN_USAGE ) T4_1
		INNER JOIN 
				(SELECT CONSTRAINT_NAME,UNIQUE_CONSTRAINT_NAME
				FROM INFORMATION_SCHEMA.REFERENTIAL_CONSTRAINTS) T4_2
		ON T4_1.CONSTRAINT_NAME = T4_2.UNIQUE_CONSTRAINT_NAME
		) T4
ON T2.UNIQUE_CONSTRAINT_NAME = T4.CONSTRAINT_NAME

LEFT JOIN
		(SELECT CONSTRAINT_NAME,CONSTRAINT_TYPE 
		FROM INFORMATION_SCHEMA.TABLE_CONSTRAINTS) T5
ON T5.CONSTRAINT_NAME = T2.UNIQUE_CONSTRAINT_NAME

WHERE T2.UNIQUE_CONSTRAINT_NAME IS NOT NULL 
