USE R1
DECLARE @TABLE_NAME VARCHAR(255) = 'Employee'

DECLARE @ORDMAX INT = (SELECT MAX(ORDINAL_POSITION) FROM Information_SCHEMA.Columns WHERE TABLE_NAME = @TABLE_NAME)
DECLARE @ORDVAR INT = 1 

DECLARE @STMT NVARCHAR(MAX) = 'CREATE TABLE ' + @TABLE_NAME + '('

WHILE @ORDVAR <= @ORDMAX 
BEGIN
	IF EXISTS(SELECT * FROM Information_SCHEMA.Columns WHERE TABLE_NAME = @TABLE_NAME AND TABLE_SCHEMA = 'dbo')
	BEGIN
		SET @STMT = @STMT + (
							SELECT COLUMN_NAME + ' ' + CASE 
															WHEN DATA_TYPE = 'VARCHAR' THEN 'VARCHAR(' + CAST(CHARACTER_MAXIMUM_LENGTH AS VARCHAR)+ ') '
															WHEN DATA_TYPE = 'NVARCHAR' THEN 'NVARCHAR(' + CAST(CHARACTER_MAXIMUM_LENGTH AS VARCHAR)+ ') '
															ELSE UPPER(DATA_TYPE) + ' '
														END
													 + CASE 
															WHEN IS_NULLABLE = 'NO'  THEN 'NOT NULL'
															ELSE 'NULL'
														END
													 + CASE WHEN @ORDVAR < @ORDMAX THEN ','
															WHEN @ORDVAR = @ORDMAX THEN ')'
															ELSE ''
														END
							FROM Information_SCHEMA.Columns 
							WHERE TABLE_NAME = @TABLE_NAME AND TABLE_SCHEMA = 'dbo' AND ORDINAL_POSITION = @ORDVAR
							)
	END
	SET @ORDVAR = @ORDVAR + 1
END

SELECT @STMT