CREATE OR ALTER VIEW Puzz11View
AS
SELECT *,ROW_NUMBER() OVER (ORDER BY @@ROWCOUNT) Rnk FROM Puzz11




DECLARE @var INT = (SELECT COUNT(*) FROM Puzz11)

DECLARE @sql NVARCHAR(MAX) = '
CREATE SEQUENCE Puzz11Seq
START WITH 1
INCREMENT BY 1
MINVALUE 1
MAXVALUE '+ CAST(@var AS VARCHAR)+' CYCLE'
EXEC(@sql)





DECLARE @var INT = (SELECT COUNT(*) FROM Puzz11)
DECLARE @st INT = 1
DECLARE @end INT = @var




WHILE (@st <= @end)
BEGIN
	SELECT * FROM Puzz11View WHERE Rnk = @st
	DECLARE @temp INT = @st

	DECLARE @SQL NVARCHAR(MAX) = 'ALTER SEQUENCE Puzz11Seq RESTART WITH ' + CAST(@st AS VARCHAR)
	EXEC(@SQL)
	SELECT NEXT VALUE FOR Puzz11Seq
 
	WHILE (NEXT VALUE FOR Puzz11Seq)

	SELECT Puzz11Seq.NEXTVAL
	SELECT LAST_VALUE FROM Puzz11Seq

			
	SET @st = @st + 1
END

